name: Test and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: nologin

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/polytech-2024
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.gha
          push: true
          tags: rg.fr-par.scw.cloud/polytech-2024/emmahrs/frontend:latest